//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O_BEBUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ENDERE
    {
        public int ENDE_ID { get; set; }
        public string ENDE_LOGRAD { get; set; }
        public string ENDE_NUMERO { get; set; }
        public string ENDE_CEP { get; set; }
        public string ENDE_COMPLE { get; set; }
        public string ENDE_BAIRRO { get; set; }
        public string ENDE_CIDADE { get; set; }
        public string ENDE_ESTADO { get; set; }
        public string ENDE_REFERE { get; set; }
        public int PESS_ID { get; set; }
    
        public virtual TB_PESSOA TB_PESSOA { get; set; }
    }
}
