//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O_BEBUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ITEPED
    {
        public int ITEP_ID { get; set; }
        public int ITEP_QTDITE { get; set; }
        public decimal ITEP_VLRITE { get; set; }
        public decimal ITEP_VLRPED { get; set; }
        public int ITEM_ID { get; set; }
        public int PEDI_ID { get; set; }
    
        public virtual TB_ITEM TB_ITEM { get; set; }
        public virtual TB_PEDIDO TB_PEDIDO { get; set; }
    }
}
