//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O_BEBUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ITEM
    {
        public TB_ITEM()
        {
            this.TB_ITEPED = new HashSet<TB_ITEPED>();
        }
    
        public int ITEM_ID { get; set; }
        public string ITEM_NOME { get; set; }
        public decimal ITEM_VALOR { get; set; }
        public decimal ITEM_PERALC { get; set; }
        public string ITEM_UNMEDI { get; set; }
        public int ITEM_ESTOQU { get; set; }
    
        public virtual ICollection<TB_ITEPED> TB_ITEPED { get; set; }
    }
}
