//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O_BEBUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PEDIDO
    {
        public TB_PEDIDO()
        {
            this.TB_ITEPED = new HashSet<TB_ITEPED>();
        }
    
        public int PEDI_ID { get; set; }
        public System.DateTime PEDI_DATA { get; set; }
        public int PESS_ID { get; set; }
        public int PAGA_ID { get; set; }
        public int PLPA_ID { get; set; }
    
        public virtual ICollection<TB_ITEPED> TB_ITEPED { get; set; }
        public virtual TB_PAGAME TB_PAGAME { get; set; }
        public virtual TB_PESSOA TB_PESSOA { get; set; }
        public virtual TB_PLPAGA TB_PLPAGA { get; set; }
    }
}
